### ISSUE TITLE
Usage of OpenDAL for database

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [cenotelie/cratery#10]
Usage of [OpenDAL](https://opendal.apache.org/) may relevant to be able to use various backend.

It may ask the question to have database trait that may be implemented by SQLX (with SQlite), or SQLX (with Postgres, etc.) or by OpenDAL with custom backend.

It open also to be able to use [oxigraph](https://github.com/oxigraph/oxigraph) as backend to store semantic data ;-) (I have already done that for one of our backend)

**Comment by woutersl** [comment]
Interesting, I didn't know this existed. It looks like it can readily replace the current storage layer that abstracts over either the FS or S3. And can be used for other kind of backends as well.
