### ISSUE TITLE
Be able to generate "shared/team" Tokens

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [cenotelie/cratery#17]
To manage easily CI in enterprise it may relevant to be able to generate Tokens that a team may manage.

Ideally it's different role than admin.

**Comment by MarcAntoine-Arnaud** [comment]
The route `/admin-tokens` display the dashboard view.

**Comment by woutersl** [comment]
Yes, this is fixed now on main.

**Comment by woutersl** [comment]
Registry-wide read-only tokens can now be created in the admin panel. Only admins can create/revoke tokens.
