### ISSUE TITLE
Configuration in new created token may not be exact

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [cenotelie/cratery#18]
The registry name is parsed from the URL.
It may not be relevant if the config field `registry.name` is different.

It may relevant to send this value to the HTML.

**Comment by MarcAntoine-Arnaud** [comment]
@woutersl it miss one on the [crate.html](https://github.com/cenotelie/cratery/blob/main/src/webapp/crate.html#L216).
Can you update it ?

**Comment by woutersl** [comment]
Fixed in [2d6e270](https://github.com/cenotelie/cratery/commit/2d6e2700d61d28fdbe11187ceabae1d30c4c3e72)
