### ISSUE TITLE
Deps checker: ignore -pre and yanked version

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [cenotelie/cratery#20]
Some crates like https://crates.io/crates/utoipa/versions publish alpha version.

It may relevant to ignore them.

It's also a specific case for https://crates.io/crates/by_address/versions
Where version > 1 are yanked/deleted.

**Comment by woutersl** [comment]
Fixed in [34e2631](https://github.com/cenotelie/cratery/commit/34e26314a146de29010be1e3c8549c6c3a7f8485)
All yanked and pre-release version are excluded from dependency analysis.
