### ISSUE TITLE
401 Unauthorized with Google oauth

### ISSUE THREAD

**Issue by francis-spliced** [cenotelie/cratery#40]
Hello,

It's probably a simple thing we forgot to do/configure. But our private instance's API is returning 401 Unauthorized.

Our Cratery instance runs on an AWS EC2 on a private domain `cratery.{our_domain}`. In the docker compose file we updated `REGISTRY_OAUTH_CLIENT_ID` & `REGISTRY_OAUTH_CLIENT_SECRET` to match our google app. The login seems to be working with google auth redirecting us to `http://cratery.{our_domain}/webapp/oauthcallback.html?state=...`, but this page makes a network call: `POST http://cratery.{our_domain}/api/v1/oauth/code` but it returns 401 Unauthorized.

Would you have any idea what we might have missed?

**Comment by francis-spliced** [comment]
After more debugging I found that google is returning 400 Bad request
```
{
    "error": "unsupported_grant_type",
    "error_description": "Invalid grant_type: "
}
```
Here: https://github.com/cenotelie/cratery/blob/ff2109644f91e51a5b5c7a997f3b8dfe8c47c146/src/services/database/users.rs#L42

**Comment by woutersl** [comment]
Strange, I just tested on the current head with the default config that uses Google and it seems to works.
That would suggest an issue on the configuration side. If the application is brand new in the google console configuration I remember that the Google tool some time to verify the app settings with the authorized scopes, etc. and login might not work before this is completed on Google's side.
Also it could be an issue with an expired authorization code, or trying to reuse the same one.
Did it ever worked, or was the login process always broken event by trying multiple times ?

**Comment by francis-spliced** [comment]
I tried locally with the default google app you provided and it is working. But no, using our own google app, it never worked, we setit up a couple of hours ago (or maybe less and I'm just impatient). It's mostlikely not an expired code as I am generating new ones everytime.

**Comment by francis-spliced** [comment]
Could you maybe share the details of your google app configuration? Maybe we missed something in there?

**Comment by francis-spliced** [comment]
After waiting more, I was able to get past the POST `api/v1/oauth/code` call, it is now working. But now cratery is somehow in a callback hell... Authenticating to google non-stop after posting the code...

![image](https://github.com/user-attachments/assets/7bd0858c-7e01-4dba-88e0-36392cfeca14)

With the oauthcallback endpoint without a response (in red in the screensot. Not sure why this is happening?

**Comment by francis-spliced** [comment]
Ok so turns out the loop is because you are requiring a secure connection for the auth cookie when not on localhost. I enabled HTTPS on our server and it is working now! thank you!
