### ISSUE TITLE
Feature: display list of documentation jobs

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [cenotelie/cratery#8]
It may useful to have a view with job statuses of documentation generation (and maybe deps checks too)

**Comment by MarcAntoine-Arnaud** [comment]
Awesome ;)
The missing part is to be able to display logs of error task.
Do you think it's easy to ad that ?

**Comment by woutersl** [comment]
On main it should be displayed in a popup when clicking on the failure badge.
I am in the process of refactoring all this a little but to handle multiple doc targets and also make the log more robust in the same process. But the interface will not change much.
